apiVersion: v1
kind: Service
metadata:
  name: qr-generator-service
  labels:
    app: qr-generator
spec:
  type: NodePort
  selector:
    app: qr-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30100